"""Add server model

Revision ID: 1dce0b3ad639
Revises: f5d0fa7ff909
Create Date: 2024-10-18 16:40:40.849263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dce0b3ad639'
down_revision: Union[str, None] = 'f5d0fa7ff909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('machine_data', sa.String(), nullable=True))
    op.add_column('server', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('server', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('server', 'max_modems',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('server', 'package_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_server_name'), 'server', ['name'], unique=False)
    op.drop_column('server', 'MachineData')
    op.drop_column('server', 'setup_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('setup_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('server', sa.Column('MachineData', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_server_name'), table_name='server')
    op.alter_column('server', 'package_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('server', 'max_modems',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('server', 'updated_at')
    op.drop_column('server', 'created_at')
    op.drop_column('server', 'machine_data')
    # ### end Alembic commands ###
