"""add setup_link to server

Revision ID: 70f23ace73ae
Revises: dd6f53530d2f
Create Date: 2024-12-10 21:41:29.332225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70f23ace73ae'
down_revision: Union[str, None] = 'dd6f53530d2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('setup_link', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server', 'setup_link')
    # ### end Alembic commands ###
